[tool.poetry]
name = "home"
version = "0.1.0"
description = ""
authors = ["Garrett Duby <[gduby36@gmail.com]>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
streamlit = "^1.38.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
